export const replayCommands = [
  'Css.addCssStyleSheet',
  'Css.removeCssStyleSheet',
  'Viewlet.addCss',
  'Viewlet.append',
  'Viewlet.appendToBody',
  'Viewlet.appendToRoot',
  'Viewlet.commitPending',
  'Viewlet.create',
  'Viewlet.createFunctionalRoot',
  'Viewlet.createPlaceholder',
  'Viewlet.dispose',
  'Viewlet.executeCommands',
  'Viewlet.patchCss',
  'Viewlet.queueCommands',
  'Viewlet.replaceChildren',
  'Viewlet.scrollSelectorBy',
  'Viewlet.sendMultiple',
  'Viewlet.setBounds',
  'Viewlet.setCheckBoxValue',
  'Viewlet.setComponentDom',
  'Viewlet.setCss',
  'Viewlet.setDom',
  'Viewlet.setDom2',
  'Viewlet.setInputValues',
  'Viewlet.setPatches',
  'Viewlet.setProperty',
  'Viewlet.setTreePatches',
  'Viewlet.setValueByName',
  'Viewlet.show',
] as const

export type ReplayCommand = (typeof replayCommands)[number]
