name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@v6
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-cacheNodeModules-${{ hashFiles('package.json', 'package-lock.json', 'packages/*/package.json', '.nvmrc', '.github/workflows/test.yml') }}
      - run: npm ci
        if: steps.npm-cache.outputs.cache-hit != 'true'
      - run: npm run build
      - run: npm test
      - run: npx playwright install --with-deps chromium
        working-directory: packages/e2e
      - run: npm run e2e
      - run: npm run lint
